name: nodeserver

services:
  server:
    build:
      dockerfile: Dockerfile_app
      context: .
    ports:
      - "3005:3005"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    build:
      dockerfile: Dockerfile_db
      context: .
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 50

  vault:
    image: vault:1.13.3
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-only-token
    ports:
      - "8200:8200"
    healthcheck:
      test: nc -z vault 8200 || exit -1
      start_period: 3s
      interval: 1s
      timeout: 4s
      retries: 50
